import { Inter } from "next/font/google";
import "./globals.css";
import GoogleAnalytics from "@/components/GoogleAnalytics";
// import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalytics />
      <body className={inter.className}>{children}</body>
      {/* <GoogleAnalytics gaId={`G-1TYYGE26JN`} /> */}
      {/* <GoogleTagManager gtmId={`G-1TYYGE26JN`} />
      <GoogleAnalytics gaId={`G-1TYYGE26JN`} /> */}
      {/* <GoogleAnalytics gaId="G-GYPX8YSP08" />
      <GoogleTagManager gtmId="G-GYPX8YSP08" /> */}
    </html>
  );
}
